name: wallpaper_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio:
  provider:
  path:
  path_provider:
  sqflite:
  http:
  flutter_staggered_grid_view:
#  cached_network_image:
  shimmer:
  win32: ^5.0.0
  animated_notch_bottom_bar:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true